### ISSUE TITLE
Lehrer werden zugespammt!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by juhu1705** [nelsbrock/NateMan#1]
Da die Lehrer E-Mail Addressen an den Schulen bekannt sind, ist es leicht diese mit Passwort zurücksetzten E-Mails zuzuspamen. Daher wäre eine bessere Regulierung durch bspw. 2 Faktor Authentifizierung hier Sinnvoll

**Comment by nelsbrock** [comment]
Dass Lehrer zugespammt werden können ist richtig, allerdings macht Zwei-Faktor-Authentifizierung bei der Passwortzurücksetzung keinen Sinn. Wie sollte das funktionieren?

**Comment by juhu1705** [comment]
Dann könnte man ein geheimes Kürzel einführen, welches die Lehrer angeben müssen???

**Comment by nelsbrock** [comment]
Ich denke nicht, dass das den Aufwand nötig wäre.
